# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DiretasJa.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets
import manifestacao
import dante

class Ui_DiretasJa(object):
    def setupUi(self, DiretasJa):
        self.DiretasJa = DiretasJa
        self.DiretasJa.setObjectName("DiretasJa")
        self.DiretasJa.resize(1042, 610)
        self.DiretasJa.setStyleSheet("background-color: rgb(148, 148, 148);\n"
"alternate-background-color: rgb(225, 225, 225);")
        self.telaPrincipal()
    def telaPrincipal(self):
        self.label = QtWidgets.QLabel(DiretasJa)
        self.label.setGeometry(QtCore.QRect(270, -20, 700, 111))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(DiretasJa)
        self.label_2.setGeometry(QtCore.QRect(155, 100, 740, 440))
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(DiretasJa)
        self.pushButton_2.setObjectName(u"pushButton")
        self.pushButton_2.setGeometry(QtCore.QRect(155, 100, 161, 61))
        self.pushButton_2.setStyleSheet("background-color: rgb(211, 211, 211); font: 800 11pt")
        self.pushButton_3 = QtWidgets.QPushButton(DiretasJa)
        self.pushButton_3.setObjectName(u"pushButton")
        self.pushButton_3.setGeometry(QtCore.QRect(735, 100, 161, 61))
        self.pushButton_3.setStyleSheet("background-color: rgb(211, 211, 211); font: 800 11pt")
        self.pushButton_4 = QtWidgets.QPushButton(DiretasJa)
        self.pushButton_4.setObjectName(u"pushButton")
        self.pushButton_4.setGeometry(QtCore.QRect(155, 300, 161, 61))
        self.pushButton_4.setStyleSheet("background-color: rgb(211, 211, 211); font: 800 11pt")
        self.pushButton_5 = QtWidgets.QPushButton(DiretasJa)
        self.pushButton_5.setObjectName(u"pushButton")
        self.pushButton_5.setGeometry(QtCore.QRect(735, 300, 161, 61))
        self.pushButton_5.setStyleSheet("background-color: rgb(211, 211, 211); font: 800 11pt")
        self.pushButton_6 = QtWidgets.QPushButton(DiretasJa)
        self.pushButton_6.setObjectName(u"pushButton")
        self.pushButton_6.setGeometry(QtCore.QRect(155, 480, 161, 61))
        self.pushButton_6.setStyleSheet("background-color: rgb(211, 211, 211); font: 800 11pt")
        self.pushButton_7 = QtWidgets.QPushButton(DiretasJa)
        self.pushButton_7.setObjectName(u"pushButton")
        self.pushButton_7.setGeometry(QtCore.QRect(735, 480, 161, 61))
        self.pushButton_7.setStyleSheet("background-color: rgb(211, 211, 211); font: 800 11pt")
        self.pushButton_8 = QtWidgets.QPushButton(DiretasJa)
        self.pushButton_8.setObjectName(u"pushButton")
        self.pushButton_8.setGeometry(QtCore.QRect(10, 15, 120, 50))
        self.pushButton_8.setStyleSheet("background-color: rgb(211, 211, 211); font: 800 9pt")
        self.pushButton_8.hide()
        self.pushButton_9 = QtWidgets.QPushButton(DiretasJa)
        self.pushButton_9.setObjectName(u"pushButton")
        self.pushButton_9.setGeometry(QtCore.QRect(440, 100, 161, 61))
        self.pushButton_9.setStyleSheet("background-color: rgb(211, 211, 211); font: 800 11pt")
        self.pushButton_10 = QtWidgets.QPushButton(DiretasJa)
        self.pushButton_10.setObjectName(u"pushButton")
        self.pushButton_10.setGeometry(QtCore.QRect(440, 300, 161, 61))
        self.pushButton_10.setStyleSheet("background-color: rgb(211, 211, 211); font: 800 11pt")
        self.pushButton_11 = QtWidgets.QPushButton(DiretasJa)
        self.pushButton_11.setObjectName(u"pushButton")
        self.pushButton_11.setGeometry(QtCore.QRect(440, 480, 161, 61))
        self.pushButton_11.setStyleSheet("background-color: rgb(211, 211, 211); font: 800 11pt")
        self.label_3 = QtWidgets.QLabel(DiretasJa)
        self.label_3.setGeometry(QtCore.QRect(160, -17, 800, 111))
        self.label_3.setObjectName("label_3")
        self.textBrowser = QtWidgets.QTextBrowser(DiretasJa)
        self.textBrowser.setGeometry(QtCore.QRect(60, 72, 920, 200))
        self.textBrowser.setStyleSheet("background-color: rgb(148, 148, 148);")
        self.textBrowser.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.textBrowser.setLineWidth(0)
        self.textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4 = QtWidgets.QLabel(DiretasJa)
        self.label_4.setGeometry(QtCore.QRect(60, 220, 900, 400))
        self.label_4.setObjectName("label_4")
        self.label_3.hide()
        self.textBrowser.hide()
        self.label_4.hide()
        self.label_5 = QtWidgets.QLabel(DiretasJa)
        self.label_5.setGeometry(QtCore.QRect(260, -17, 800, 111))
        self.label_5.setObjectName("label_5")
        self.textBrowser_2 = QtWidgets.QTextBrowser(DiretasJa)
        self.textBrowser_2.setGeometry(QtCore.QRect(60, 130, 920, 800))
        self.textBrowser_2.setStyleSheet("background-color: rgb(148, 148, 148);")
        self.textBrowser_2.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.textBrowser_2.setLineWidth(0)
        self.textBrowser_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textBrowser_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textBrowser_2.setObjectName("textBrowser2")
        self.textBrowser_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.textBrowser_2.hide()
        self.label_5.hide()
        self.label_6 = QtWidgets.QLabel(DiretasJa)
        self.label_6.setGeometry(QtCore.QRect(350,-17, 800, 111))
        self.label_6.setObjectName("label_6")
        self.textBrowser_3 = QtWidgets.QTextBrowser(DiretasJa)
        self.textBrowser_3.setGeometry(QtCore.QRect(80, 110, 920, 800))
        self.textBrowser_3.setStyleSheet("background-color: rgb(148, 148, 148);")
        self.textBrowser_3.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.textBrowser_3.setLineWidth(0)
        self.textBrowser_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textBrowser_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textBrowser_3.setObjectName("textBrowser3")
        self.textBrowser_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.textBrowser_3.hide()
        self.label_6.hide()
        self.label_7 = QtWidgets.QLabel(DiretasJa)
        self.label_7.setGeometry(QtCore.QRect(200,-17, 800, 111))
        self.label_7.setObjectName("label_7")
        self.textBrowser_4 = QtWidgets.QTextBrowser(DiretasJa)
        self.textBrowser_4.setGeometry(QtCore.QRect(80, 110, 920, 800))
        self.textBrowser_4.setStyleSheet("background-color: rgb(148, 148, 148);")
        self.textBrowser_4.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.textBrowser_4.setLineWidth(0)
        self.textBrowser_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textBrowser_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textBrowser_4.setObjectName("textBrowser4")
        self.textBrowser_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.textBrowser_4.hide()
        self.label_7.hide()
        self.label_8 = QtWidgets.QLabel(DiretasJa)
        self.label_8.setGeometry(QtCore.QRect(360,-17, 800, 111))
        self.label_8.setObjectName("label_8")
        self.textBrowser_5 = QtWidgets.QTextBrowser(DiretasJa)
        self.textBrowser_5.setGeometry(QtCore.QRect(80, 110, 920, 800))
        self.textBrowser_5.setStyleSheet("background-color: rgb(148, 148, 148);")
        self.textBrowser_5.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.textBrowser_5.setLineWidth(0)
        self.textBrowser_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textBrowser_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textBrowser_5.setObjectName("textBrowser5")
        self.textBrowser_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.textBrowser_5.hide()
        self.label_8.hide()
        self.label_9 = QtWidgets.QLabel(DiretasJa)
        self.label_9.setGeometry(QtCore.QRect(435,-17, 800, 111))
        self.label_9.setObjectName("label_9")
        self.textBrowser_6 = QtWidgets.QTextBrowser(DiretasJa)
        self.textBrowser_6.setGeometry(QtCore.QRect(80, 90, 920, 800))
        self.textBrowser_6.setStyleSheet("background-color: rgb(148, 148, 148);")
        self.textBrowser_6.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.textBrowser_6.setLineWidth(0)
        self.textBrowser_6.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textBrowser_6.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textBrowser_6.setObjectName("textBrowser6")
        self.textBrowser_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.textBrowser_6.hide()
        self.label_9.hide()
        self.label_10 = QtWidgets.QLabel(DiretasJa)
        self.label_10.setGeometry(QtCore.QRect(370,-17, 800, 111))
        self.label_10.setObjectName("label_10")
        self.textBrowser_7 = QtWidgets.QTextBrowser(DiretasJa)
        self.textBrowser_7.setGeometry(QtCore.QRect(80, 90, 920, 800))
        self.textBrowser_7.setStyleSheet("background-color: rgb(148, 148, 148);")
        self.textBrowser_7.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.textBrowser_7.setLineWidth(0)
        self.textBrowser_7.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textBrowser_7.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textBrowser_7.setObjectName("textBrowser7")
        self.textBrowser_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.textBrowser_7.hide()
        self.label_10.hide()
        self.label_11 = QtWidgets.QLabel(DiretasJa)
        self.label_11.setGeometry(QtCore.QRect(420,-17, 800, 111))
        self.label_11.setObjectName("label_11")
        self.textBrowser_8 = QtWidgets.QTextBrowser(DiretasJa)
        self.textBrowser_8.setGeometry(QtCore.QRect(80, 90, 920, 800))
        self.textBrowser_8.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.textBrowser_8.setLineWidth(0)
        self.textBrowser_8.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textBrowser_8.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textBrowser_8.setObjectName("textBrowser8")
        self.textBrowser_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.textBrowser_8.hide()
        self.label_11.hide()
        self.label_12 = QtWidgets.QLabel(DiretasJa)
        self.label_12.setGeometry(QtCore.QRect(400,-17, 800, 111))
        self.label_12.setObjectName("label_12")
        self.textBrowser_9 = QtWidgets.QTextBrowser(DiretasJa)
        self.textBrowser_9.setGeometry(QtCore.QRect(110, 150, 920, 800))
        self.textBrowser_9.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.textBrowser_9.setLineWidth(0)
        self.textBrowser_9.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textBrowser_9.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textBrowser_9.setObjectName("textBrowser9")
        self.textBrowser_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.textBrowser_9.hide()
        self.label_12.hide()
        self.pushButton_2.clicked.connect(self.indiretas)
        self.pushButton_3.clicked.connect(self.motivacao)
        self.pushButton_4.clicked.connect(self.primeiras)
        self.pushButton_5.clicked.connect(self.apice)
        self.pushButton_6.clicked.connect(self.resolucao)
        self.pushButton_7.clicked.connect(self.creditos)
        self.pushButton_11.clicked.connect(self.fontes)
        self.pushButton_10.clicked.connect(self.liderancas)
        self.pushButton_9.clicked.connect(self.contexto)
        self.pushButton_8.clicked.connect(self.voltar)
        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(DiretasJa)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.DiretasJa.setWindowTitle(_translate("DiretasJa", "DiretasJa"))
        self.label.setText(_translate("DiretasJa", "<html><head/><body><p><span style=\" font-size:72pt; font-weight:700; font-style:italic; color:#000000;\">DIRETAS JA</span></p></body></html>"))
        self.label_2.setText(_translate("DiretasJa", "<html><head/><body><p><img src=\":/newPrefix/manifestacao2.jpg\"/></p></body></html>"))
        self.pushButton_2.setText(_translate("DiretasJa", u"ELEI\u00c7\u00d5ES \n INDIRETAS", None))
        self.pushButton_3.setText(_translate("DiretasJa", u"MOTIVA\u00c7\u00c3O", None))
        self.pushButton_4.setText(_translate("DiretasJa", u"PRIMEIRAS \n MANIFESTA\u00c7\u00d5ES", None))
        self.pushButton_5.setText(_translate("DiretasJa", u"\u00c1PICE", None))
        self.pushButton_6.setText(_translate("DiretasJa", u"RESOLU\u00c7\u00c3O", None))
        self.pushButton_7.setText(_translate("DiretasJa", u"CR\u00c9DITOS", None))
        self.pushButton_9.setText(_translate("DiretasJa", u"PEC n° 05/1983", None))
        self.pushButton_10.setText(_translate("DiretasJa", u"LIDERAN\u00c7AS", None))
        self.pushButton_11.setText(_translate("DiretasJa", u"FONTES", None))
    def indiretas(self):
        self.label.hide()
        self.label_2.hide()
        self.pushButton_2.hide()
        self.pushButton_3.hide()
        self.pushButton_4.hide()
        self.pushButton_5.hide()
        self.pushButton_6.hide()
        self.pushButton_7.hide()
        self.pushButton_8.show()
        self.pushButton_9.hide()
        self.pushButton_10.hide()
        self.pushButton_11.hide()
        self.label_5.show()
        self.textBrowser_2.show()
        self.retranslateUiindiretas()
    def contexto(self):
        self.label.hide()
        self.label_2.hide()
        self.pushButton_2.hide()
        self.pushButton_3.hide()
        self.pushButton_4.hide()
        self.pushButton_5.hide()
        self.pushButton_6.hide()
        self.pushButton_7.hide()
        self.pushButton_8.show()
        self.pushButton_9.hide()
        self.pushButton_10.hide()
        self.pushButton_11.hide()
        self.label_3.show()
        self.textBrowser.show()
        self.label_4.show()
        self.retranslateUicontexto()
    def motivacao(self):
        self.label.hide()
        self.label_2.hide()
        self.pushButton_2.hide()
        self.pushButton_3.hide()
        self.pushButton_4.hide()
        self.pushButton_5.hide()
        self.pushButton_6.hide()
        self.pushButton_7.hide()
        self.pushButton_8.show()
        self.pushButton_9.hide()
        self.pushButton_10.hide()
        self.pushButton_11.hide()
        self.label_6.show()
        self.textBrowser_3.show()
        self.retranslateUimotivacao()
    def primeiras(self):
        self.label.hide()
        self.label_2.hide()
        self.pushButton_2.hide()
        self.pushButton_3.hide()
        self.pushButton_4.hide()
        self.pushButton_5.hide()
        self.pushButton_6.hide()
        self.pushButton_7.hide()
        self.pushButton_8.show()
        self.pushButton_9.hide()
        self.pushButton_10.hide()
        self.pushButton_11.hide()
        self.label_7.show()
        self.textBrowser_4.show()
        self.retranslateUiprimeiras()
    def liderancas(self):
        self.label.hide()
        self.label_2.hide()
        self.pushButton_2.hide()
        self.pushButton_3.hide()
        self.pushButton_4.hide()
        self.pushButton_5.hide()
        self.pushButton_6.hide()
        self.pushButton_7.hide()
        self.pushButton_8.show()
        self.pushButton_9.hide()
        self.pushButton_10.hide()
        self.pushButton_11.hide()
        self.label_8.show()
        self.textBrowser_5.show()
        self.retranslateUiliderancas()
    def apice(self):
        self.label.hide()
        self.label_2.hide()
        self.pushButton_2.hide()
        self.pushButton_3.hide()
        self.pushButton_4.hide()
        self.pushButton_5.hide()
        self.pushButton_6.hide()
        self.pushButton_7.hide()
        self.pushButton_8.show()
        self.pushButton_9.hide()
        self.pushButton_10.hide()
        self.pushButton_11.hide()
        self.label_9.show()
        self.textBrowser_6.show()
        self.retranslateUiapice()
    def resolucao(self):
        self.label.hide()
        self.label_2.hide()
        self.pushButton_2.hide()
        self.pushButton_3.hide()
        self.pushButton_4.hide()
        self.pushButton_5.hide()
        self.pushButton_6.hide()
        self.pushButton_7.hide()
        self.pushButton_8.show()
        self.pushButton_9.hide()
        self.pushButton_10.hide()
        self.pushButton_11.hide()
        self.label_10.show()
        self.textBrowser_7.show()
        self.retranslateUiresolucao()
    def fontes(self):
        self.label.hide()
        self.label_2.hide()
        self.pushButton_2.hide()
        self.pushButton_3.hide()
        self.pushButton_4.hide()
        self.pushButton_5.hide()
        self.pushButton_6.hide()
        self.pushButton_7.hide()
        self.pushButton_8.show()
        self.pushButton_9.hide()
        self.pushButton_10.hide()
        self.pushButton_11.hide()
        self.label_11.show()
        self.textBrowser_8.show()
        self.retranslateUifontes()
    def creditos(self):
        self.label.hide()
        self.label_2.hide()
        self.pushButton_2.hide()
        self.pushButton_3.hide()
        self.pushButton_4.hide()
        self.pushButton_5.hide()
        self.pushButton_6.hide()
        self.pushButton_7.hide()
        self.pushButton_8.show()
        self.pushButton_9.hide()
        self.pushButton_10.hide()
        self.pushButton_11.hide()
        self.label_12.show()
        self.textBrowser_9.show()
        self.retranslateUicreditos()
    def voltar(self):
        self.label_3.hide()
        self.textBrowser.hide()
        self.label_4.hide()
        self.label_5.hide()
        self.textBrowser_2.hide()
        self.textBrowser_3.hide()
        self.label_6.hide()
        self.label_7.hide()
        self.textBrowser_4.hide()
        self.label_8.hide()
        self.textBrowser_5.hide()
        self.label_9.hide()
        self.textBrowser_6.hide()
        self.label_10.hide()
        self.textBrowser_7.hide()
        self.label_11.hide()
        self.textBrowser_8.hide()
        self.label_12.hide()
        self.textBrowser_9.hide()
        self.label.show()
        self.label_2.show()
        self.pushButton_2.show()
        self.pushButton_3.show()
        self.pushButton_4.show()
        self.pushButton_5.show()
        self.pushButton_6.show()
        self.pushButton_7.show()
        self.pushButton_8.hide()
        self.pushButton_9.show()
        self.pushButton_10.show()
        self.pushButton_11.show()
    def retranslateUicontexto(self):
        _translate = QtCore.QCoreApplication.translate
        self.pushButton_8.setText(_translate("DiretasJa", u"VOLTAR", None))
        self.label_3.setText(_translate("DiretasJa", "<html><head/><body><p><span style=\" font-size:40pt; font-weight:700; font-style:italic\">EMENDA DANTE DE OLIVEIRA</span></p></body></html>"))
        self.textBrowser.setHtml(_translate("DiretasJa", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight: 700\">Em 1983, o deputado federal Dante de Oliveira (PMDB-MT) apresentou a Proposta de Emenda Constitucional n° 05/1983 ao Congresso Nacional. A PEC, que ficou conhecida como 'Emenda Dante de Oliveira', previa reestabelecer as eleições diretas para a Presidência da República no Brasil.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight: 700\">As manifestações e comícios a favor das eleições diretas ganharam muita força após a apresentação da emenda, fazendo com que a enorme pressão popular afetasse os parlamentares.</span></p></body></html>"))
        self.label_4.setText(_translate("DiretasJa", "<html><head/><body><p><img src=\":/Dante/dante2.jpg\"/></p></body></html>"))
    def retranslateUiindiretas(self):
        _translate = QtCore.QCoreApplication.translate
        self.pushButton_8.setText(_translate("DiretasJa", u"VOLTAR", None))
        self.label_5.setText(_translate("DiretasJa", "<html><head/><body><p><span style=\" font-size:40pt; font-weight:700; font-style:italic\">ELEIÇÕES INDIRETAS</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("DiretasJa", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:23pt; font-weight: 700\">Devido às sequências de atos institucionais, o povo estava gradualmente  perdendo os seus direitos políticos. O principal deles foi o direito de votar para a Presidência da República. Assim, foi instaurado no Brasil um sistema de eleições indiretas, ou seja, o Presidente da República não seria eleito diretamente pelo povo, mas sim por um colégio eleitoral, que durante o regime militar foi o Congresso Nacional.</span></p></body></html>"))
    def retranslateUimotivacao(self):
        _translate = QtCore.QCoreApplication.translate
        self.pushButton_8.setText(_translate("DiretasJa", u"VOLTAR", None))
        self.label_6.setText(_translate("DiretasJa", "<html><head/><body><p><span style=\" font-size:40pt; font-weight:700; font-style:italic\">MOTIVAÇÃO</span></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("DiretasJa", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:23pt; font-weight: 700\">Além da Emenda Dante de Oliveira, um outro fator que contribuiu para o crescimento do movimento a favor das eleições diretas foi a grande recessão econômica e o agravamento da inflação. Estima-se que em 1983 a inflação chegou a alcançar a taxa de 239%, e a dívida externa que comprometia boa parte das riquezas nacionais afastava investidores. Ademais, o governo militar atravessava seu período final em meio a uma crise de desgaste que se refletiu em uma crise interna, culminando com a retirada do presidente Figueiredo das articulações para a sucessão presidencial.</span></p></body></html>"))
    def retranslateUiprimeiras(self):
        _translate = QtCore.QCoreApplication.translate
        self.pushButton_8.setText(_translate("DiretasJa", u"VOLTAR", None))
        self.label_7.setText(_translate("DiretasJa", "<html><head/><body><p><span style=\" font-size:40pt; font-weight:700; font-style:italic\">PRIMEIRAS MANIFESTAÇÕES</span></p></body></html>"))
        self.textBrowser_4.setHtml(_translate("DiretasJa", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; font-weight: 700\">Ao longo de 1983, eventos em prol das eleições diretas já aconteciam no Brasil. A primeira manifestação pública a favor das eleições diretas ocorreu em no dia 31 de março de 1983, no recém-emancipado município de Abreu e Lima, mas teve baixa adesão. Posteriormente, Ulysses Guimarães parlamentar filiado ao PMDB e um dos principais articuladores do movimento promoveu um debate na Universidade de Goiás. Seu ato teve como resultado a manifestação de aproximadamente 5 mil pessoas a favor da volta das eleições diretas. Outras manifestações aconteceram nesse mesmo ano, como a de São Paulo em 27 de novembro, que alcançou 15 mil pessoas. Entretanto, foi apenas em 1984 que o movimento Diretas Já ganhou massa crítica.</span></p></body></html>"))
    def retranslateUiliderancas(self):
        _translate = QtCore.QCoreApplication.translate
        self.pushButton_8.setText(_translate("DiretasJa", u"VOLTAR", None))
        self.label_8.setText(_translate("DiretasJa", "<html><head/><body><p><span style=\" font-size:40pt; font-weight:700; font-style:italic\">LIDERANÇAS</span></p></body></html>"))
        self.textBrowser_5.setHtml(_translate("DiretasJa", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; font-weight: 700\">As principais lideranças das Diretas Já eram políticos, artistas e intelectuais. Dentre os líderes políticos que tiveram suas carreiras interrompidas por algum ato arbitrário da ditadura ou fizeram dos seus mandatos uma resistência, destacaram-se Tancredo Neves, Ulysses Guimarães, Franco Montoro, Mário Covas, Leonel Brizola, Lula e Dante de Oliveira. Dentre outras personalidades em geral que participaram do movimento, Heráclito Fontoura Sobral, Sócrates (futebolista), Fafá de Belém, Chico Boarque, Martinho da Vila e Mário Lago são algumas das várias personalidades que tiveram constante presença nas manifestações e comícios.</span></p></body></html>"))
    def retranslateUiapice(self):
        _translate = QtCore.QCoreApplication.translate
        self.pushButton_8.setText(_translate("DiretasJa", u"VOLTAR", None))
        self.label_9.setText(_translate("DiretasJa", "<html><head/><body><p><span style=\" font-size:40pt; font-weight:700; font-style:italic\">ÁPICE</span></p></body></html>"))
        self.textBrowser_6.setHtml(_translate("DiretasJa", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight: 700\">O ápice do movimento ocorreu durante os quatro primeiros meses de 1984, quando as manifestações estavam tornando-se gigantes. Em 12 de janeiro, Curitiba foi palco do primeiro grande comicio em todo o país da campanha Diretas Já, com cerca de 30 mil pessoas presentes. Em 25 de janeiro, em São Paulo, na Praça da Sé, justamente no dia do aniversário da cidade, o comício conquistou de vez as ruas com o expressivo número de 300 mil pessoas gritando por Diretas Já!. O movimento acumulava cada vez mais pessoas indo às ruas, e isso se mostrou ainda mais claro nas capitais de Minas Gerais, Rio de Janeiro e São Paulo. Em 24 de fevereiro, foi a vez de Belo Horizonte, com a marca de 400 mil pessoas se manifestando na Praça da Rodoviária, no início da Avenida Afonso Pena, tendo o recorde de público até então. As duas maiores manifestações da Diretas Já ocorreram em abril: em 10 de abril, mais de um milhão de pessoas se reuniram nas proximidades da Igreja da Candelária, na cidade do Rio de Janeiro. O estrondoso comício ficou conhecido como 'Comício da Candelária', em referência ao local onde foi realizada a manifestação. Seis dias depois, o Vale do Anhangabaú, na cidade de São Paulo, ficou lotada com 1,5 milhões de manifestantes lutando por eleições diretas, sendo esta a última manifestação da Diretas Já, e também a manifestação que detém o recorde de pessoas de toda a história do movimento.</span></p></body></html>"))
    def retranslateUiresolucao(self):
        _translate = QtCore.QCoreApplication.translate
        self.pushButton_8.setText(_translate("DiretasJa", u"VOLTAR", None))
        self.label_10.setText(_translate("DiretasJa", "<html><head/><body><p><span style=\" font-size:40pt; font-weight:700; font-style:italic\">RESOLUÇÃO</span></p></body></html>"))
        self.textBrowser_7.setHtml(_translate("DiretasJa", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight: 700\">Mesmo com a alta pressão popular e grande rejeição à Ditadura Militar, a Emenda Dante de Oliveira não foi aprovada na Câmara dos Deputados. A proposta teve 298 votos de deputados favoráveis, sendo que ela precisava de pelo menos 320 votos para que seguisse ao Senado. Com a rejeição da emenda, a eleição para Presidente da República de 1985 foi novamente indireta. Entretanto, articulações da oposição ao regime militar, em especial do PMDB, endossadas pela mídia e com forte apoio popular, racharam a base governista que era maioria no Congresso Nacional, ocasionando a escolha do oposicionista Tancredo Neves (PMDB) como presidente da república, derrotando o candidato Paulo Maluf. Apesar de ter sido eleito, Tancredo jamais tomou posse: sofrendo de um tumor benigno, ele foi hospitalizado no dia anterior a sua posse, e veio ao óbito em 21 de abril de 1985. Assim, o velho aliado dos governos militares acabou sendo o primeiro presidente civil brasileiro desde 1964: José Sarney. Posteriormente, na publicação da Constituição de 1988, a eleição direta foi oficialmente determinada e instaurada para o cargo de Presidente da República.</span></p></body></html>"))
    def retranslateUifontes(self):
        _translate = QtCore.QCoreApplication.translate
        self.pushButton_8.setText(_translate("DiretasJa", u"VOLTAR", None))
        self.label_11.setText(_translate("DiretasJa", "<html><head/><body><p><span style=\" font-size:40pt; font-weight:700; font-style:italic\">FONTES</span></p></body></html>"))
        self.textBrowser_8.setHtml(_translate("DiretasJa", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; text-decoration: underline; background-color:#1e1e1e\">https://mundoeducacao.uol.com.br/historiadobrasil/diretas-ja.htm</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; text-decoration: underline; background-color:#1e1e1e\">https://www.saopaulo.sp.gov.br/conhecasp/historia/diretas-ja/</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; text-decoration: underline; background-color:#1e1e1e\">https://riomemorias.com.br/memoria/comicio-da-candelaria-diretas-ja/</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px;"
                        " -qt-block-indent:0; text-indent:0px; text-decoration: underline; background-color:#1e1e1e\">https://pt.wikipedia.org/wiki/Diretas_J%C3%A1</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; text-decoration: underline; background-color:#1e1e1e\">https://brasilescola.uol.com.br/politica/eleicoes-indiretas-no-brasil.htm</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; text-decoration: underline; background-color:#1e1e1e\">http://g1.globo.com/sao-paulo/noticia/2014/04/famoso-comicio-do-movimento-diretas-ja-completa-30-anos.html</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; text-decoration: underline; background-color:#1e1e1e\">https://www.todamateria.com.br/diretas-ja/</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; text-decoration: underline; background-color:#1e1e1e\">http://querepublicaeessa.an.gov.br/temas/172-diretas-ja-o-povo-volta-as-ruas.html</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-in"
                        "dent:0px; text-decoration: underline; background-color:#1e1e1e\">https://www.gazetadopovo.com.br/vida-publica/curitiba-foi-pioneira-na-campanha-bdzz1yc2vvn0dlfkh33y08r4e/</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; text-decoration: underline; background-color:#1e1e1e\">https://www.tse.jus.br/eleitor/glossario/termos/eleicao-indireta</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; text-decoration: underline; background-color:#1e1e1e\">https://pt.wikipedia.org/wiki/Proposta_de_Emenda_Constitucional_Dante_de_Oliveira</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; text-decoration: underline; background-color:#1e1e1e\">https://www.infoescola.com/historia-do-brasil/emenda-constitucional-dante-de-oliveira/</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; text-decoration: underline; background-color:#1e1e1e\">http://circuitomt.com.br/editorias/perolas-online/140440-emenda-constitucional-de-dante-de-oliveira-que-conduziria-pais-a-eleicao-direta-completa-35-anos.htm"
                        "l</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; text-decoration: underline; background-color:#1e1e1e\">https://www25.senado.leg.br/web/atividade/materias/-/materia/18035</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; text-decoration: underline; background-color:#1e1e1e\">https://memoriaglobo.globo.com/erros/diretas-ja/</p></body></html>", None))
    def retranslateUicreditos(self):
        _translate = QtCore.QCoreApplication.translate
        self.pushButton_8.setText(_translate("DiretasJa", u"VOLTAR", None))
        self.label_12.setText(_translate("DiretasJa", "<html><head/><body><p><span style=\" font-size:40pt; font-weight:700; font-style:italic\">CRÉDITOS</span></p></body></html>"))
        self.textBrowser_9.setHtml(_translate("DiretasJa", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:26pt;\">Autor do Programa: Gabriel de Souza Santos</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:26pt;\">Programa\u00e7\u00e3o: Gabriel de Souza Santos</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:26pt;\">Design: Gabriel de Souza Santos</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:26pt;\">Ano: 2021</p>\n"
"<p style=\" marg"
                        "in-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;  font-size:26pt;\">Ferramentas utilizadas: Python 3.9.6 (Programa\u00e7\u00e3o), Qt Designer (Design), PyQt6, PySide6</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:26pt;\">Código-fonte: https://github.com/Kalest3/DiretasJa</p></body></html>"))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DiretasJa = QtWidgets.QDialog()
    ui = Ui_DiretasJa()
    ui.setupUi(DiretasJa)
    DiretasJa.show()
    sys.exit(app.exec())
