# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DiretasJa.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets
import manifestacao
import dante

class Ui_DiretasJa(object):
    def setupUi(self, DiretasJa):
        self.DiretasJa = DiretasJa
        self.DiretasJa.setObjectName("DiretasJa")
        self.DiretasJa.resize(1042, 610)
        self.DiretasJa.setStyleSheet("background-color: rgb(148, 148, 148);\n"
"alternate-background-color: rgb(225, 225, 225);")
        self.telaPrincipal()
    def telaPrincipal(self):
        self.diretasLabel = QtWidgets.QLabel(DiretasJa)
        self.diretasLabel.setGeometry(QtCore.QRect(270, -20, 700, 111))
        self.diretasLabel.setObjectName("diretasLabel")
        self.manifestacaoImg = QtWidgets.QLabel(DiretasJa)
        self.manifestacaoImg.setGeometry(QtCore.QRect(155, 100, 740, 440))
        self.manifestacaoImg.setObjectName("manifestacaoImg")
        self.indiretasb = QtWidgets.QPushButton(DiretasJa)
        self.indiretasb.setObjectName("indiretasButton")
        self.indiretasb.setGeometry(QtCore.QRect(155, 100, 161, 61))
        self.indiretasb.setStyleSheet("background-color: rgb(211, 211, 211); font: 800 11pt")
        self.contextob = QtWidgets.QPushButton(DiretasJa)
        self.contextob.setObjectName("contextoButton")
        self.contextob.setGeometry(QtCore.QRect(440, 100, 161, 61))
        self.contextob.setStyleSheet("background-color: rgb(211, 211, 211); font: 800 11pt")
        self.motivacaob = QtWidgets.QPushButton(DiretasJa)
        self.motivacaob.setObjectName("motivacaoButton")
        self.motivacaob.setGeometry(QtCore.QRect(735, 100, 161, 61))
        self.motivacaob.setStyleSheet("background-color: rgb(211, 211, 211); font: 800 11pt")
        self.primeirasb = QtWidgets.QPushButton(DiretasJa)
        self.primeirasb.setObjectName("primeirasButton")
        self.primeirasb.setGeometry(QtCore.QRect(155, 300, 161, 61))
        self.primeirasb.setStyleSheet("background-color: rgb(211, 211, 211); font: 800 11pt")
        self.apiceb = QtWidgets.QPushButton(DiretasJa)
        self.apiceb.setObjectName("apiceButton")
        self.apiceb.setGeometry(QtCore.QRect(735, 300, 161, 61))
        self.apiceb.setStyleSheet("background-color: rgb(211, 211, 211); font: 800 11pt")
        self.resolucaob = QtWidgets.QPushButton(DiretasJa)
        self.resolucaob.setObjectName("resolucaoButton")
        self.resolucaob.setGeometry(QtCore.QRect(155, 480, 161, 61))
        self.resolucaob.setStyleSheet("background-color: rgb(211, 211, 211); font: 800 11pt")
        self.creditosb = QtWidgets.QPushButton(DiretasJa)
        self.creditosb.setObjectName("creditosButton")
        self.creditosb.setGeometry(QtCore.QRect(735, 480, 161, 61))
        self.creditosb.setStyleSheet("background-color: rgb(211, 211, 211); font: 800 11pt")
        self.voltarb = QtWidgets.QPushButton(DiretasJa)
        self.voltarb.setObjectName("voltarButton")
        self.voltarb.setGeometry(QtCore.QRect(10, 15, 120, 50))
        self.voltarb.setStyleSheet("background-color: rgb(211, 211, 211); font: 800 9pt")
        self.liderancasb = QtWidgets.QPushButton(DiretasJa)
        self.liderancasb.setObjectName("liderancasButton")
        self.liderancasb.setGeometry(QtCore.QRect(440, 300, 161, 61))
        self.liderancasb.setStyleSheet("background-color: rgb(211, 211, 211); font: 800 11pt")
        self.fontesb = QtWidgets.QPushButton(DiretasJa)
        self.fontesb.setObjectName("fontesButton")
        self.fontesb.setGeometry(QtCore.QRect(440, 480, 161, 61))
        self.fontesb.setStyleSheet("background-color: rgb(211, 211, 211); font: 800 11pt")
        self.indiretasTitulo = QtWidgets.QLabel(DiretasJa)
        self.indiretasTitulo.setGeometry(QtCore.QRect(260, -17, 800, 111))
        self.indiretasTitulo.setObjectName("indiretasTitulo")
        self.indiretasTexto = QtWidgets.QTextBrowser(DiretasJa)
        self.indiretasTexto.setGeometry(QtCore.QRect(60, 130, 920, 800))
        self.indiretasTexto.setStyleSheet("background-color: rgb(148, 148, 148);")
        self.indiretasTexto.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.indiretasTexto.setLineWidth(0)
        self.indiretasTexto.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.indiretasTexto.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.indiretasTexto.setObjectName("indiretasTexto")
        self.indiretasTexto.setStyleSheet("color: rgb(255, 255, 255);")
        self.contextoTitulo = QtWidgets.QLabel(DiretasJa)
        self.contextoTitulo.setGeometry(QtCore.QRect(160, -17, 800, 111))
        self.contextoTitulo.setObjectName("contextoTitulo")
        self.danteImg = QtWidgets.QLabel(DiretasJa)
        self.danteImg.setGeometry(QtCore.QRect(60, 220, 900, 400))
        self.danteImg.setObjectName("danteImg")
        self.contextoTexto = QtWidgets.QTextBrowser(DiretasJa)
        self.contextoTexto.setGeometry(QtCore.QRect(60, 72, 900, 150))
        self.contextoTexto.setStyleSheet("background-color: rgb(148, 148, 148);")
        self.contextoTexto.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.contextoTexto.setLineWidth(0)
        self.contextoTexto.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.contextoTexto.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.contextoTexto.setObjectName("textBrowser2")
        self.contextoTexto.setStyleSheet("color: rgb(255, 255, 255);")
        self.motivacaoTitulo = QtWidgets.QLabel(DiretasJa)
        self.motivacaoTitulo.setGeometry(QtCore.QRect(350,-17, 800, 111))
        self.motivacaoTitulo.setObjectName("motivacaoTitulo")
        self.motivacaoTexto = QtWidgets.QTextBrowser(DiretasJa)
        self.motivacaoTexto.setGeometry(QtCore.QRect(80, 110, 920, 800))
        self.motivacaoTexto.setStyleSheet("background-color: rgb(148, 148, 148);")
        self.motivacaoTexto.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.motivacaoTexto.setLineWidth(0)
        self.motivacaoTexto.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.motivacaoTexto.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.motivacaoTexto.setObjectName("motivacaoTexto")
        self.motivacaoTexto.setStyleSheet("color: rgb(255, 255, 255);")
        self.primeirasTitulo = QtWidgets.QLabel(DiretasJa)
        self.primeirasTitulo.setGeometry(QtCore.QRect(200,-17, 800, 111))
        self.primeirasTitulo.setObjectName("primeirasTitulo")
        self.primeirasTexto = QtWidgets.QTextBrowser(DiretasJa)
        self.primeirasTexto.setGeometry(QtCore.QRect(80, 110, 920, 800))
        self.primeirasTexto.setStyleSheet("background-color: rgb(148, 148, 148);")
        self.primeirasTexto.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.primeirasTexto.setLineWidth(0)
        self.primeirasTexto.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.primeirasTexto.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.primeirasTexto.setObjectName("textBrowser4")
        self.primeirasTexto.setStyleSheet("color: rgb(255, 255, 255);")
        self.liderancasTitulo = QtWidgets.QLabel(DiretasJa)
        self.liderancasTitulo.setGeometry(QtCore.QRect(360,-17, 800, 111))
        self.liderancasTitulo.setObjectName("liderancasTitulo")
        self.liderancasTexto = QtWidgets.QTextBrowser(DiretasJa)
        self.liderancasTexto.setGeometry(QtCore.QRect(80, 110, 920, 800))
        self.liderancasTexto.setStyleSheet("background-color: rgb(148, 148, 148);")
        self.liderancasTexto.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.liderancasTexto.setLineWidth(0)
        self.liderancasTexto.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.liderancasTexto.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.liderancasTexto.setObjectName("textBrowser5")
        self.liderancasTexto.setStyleSheet("color: rgb(255, 255, 255);")
        self.apiceTitulo = QtWidgets.QLabel(DiretasJa)
        self.apiceTitulo.setGeometry(QtCore.QRect(435,-17, 800, 111))
        self.apiceTitulo.setObjectName("apiceTitulo")
        self.apiceTexto = QtWidgets.QTextBrowser(DiretasJa)
        self.apiceTexto.setGeometry(QtCore.QRect(80, 90, 920, 800))
        self.apiceTexto.setStyleSheet("background-color: rgb(148, 148, 148);")
        self.apiceTexto.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.apiceTexto.setLineWidth(0)
        self.apiceTexto.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.apiceTexto.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.apiceTexto.setObjectName("textBrowser6")
        self.apiceTexto.setStyleSheet("color: rgb(255, 255, 255);")
        self.resolucaoTitulo = QtWidgets.QLabel(DiretasJa)
        self.resolucaoTitulo.setGeometry(QtCore.QRect(370,-17, 800, 111))
        self.resolucaoTitulo.setObjectName("resolucaoTitulo")
        self.resolucaoTexto = QtWidgets.QTextBrowser(DiretasJa)
        self.resolucaoTexto.setGeometry(QtCore.QRect(80, 90, 920, 800))
        self.resolucaoTexto.setStyleSheet("background-color: rgb(148, 148, 148);")
        self.resolucaoTexto.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.resolucaoTexto.setLineWidth(0)
        self.resolucaoTexto.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.resolucaoTexto.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.resolucaoTexto.setObjectName("textBrowser7")
        self.resolucaoTexto.setStyleSheet("color: rgb(255, 255, 255);")
        self.fontesTitulo = QtWidgets.QLabel(DiretasJa)
        self.fontesTitulo.setGeometry(QtCore.QRect(420,-17, 800, 111))
        self.fontesTitulo.setObjectName("fontesTitulo")
        self.fontesTexto = QtWidgets.QTextBrowser(DiretasJa)
        self.fontesTexto.setGeometry(QtCore.QRect(80, 90, 920, 800))
        self.fontesTexto.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.fontesTexto.setLineWidth(0)
        self.fontesTexto.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.fontesTexto.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.fontesTexto.setObjectName("textBrowser8")
        self.fontesTexto.setStyleSheet("color: rgb(255, 255, 255);")
        self.creditosTitulo = QtWidgets.QLabel(DiretasJa)
        self.creditosTitulo.setGeometry(QtCore.QRect(400,-17, 800, 111))
        self.creditosTitulo.setObjectName("creditosTitulo")
        self.creditosTexto = QtWidgets.QTextBrowser(DiretasJa)
        self.creditosTexto.setGeometry(QtCore.QRect(110, 150, 920, 800))
        self.creditosTexto.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.creditosTexto.setLineWidth(0)
        self.creditosTexto.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.creditosTexto.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.creditosTexto.setObjectName("textBrowser9")
        self.creditosTexto.setStyleSheet("color: rgb(255, 255, 255);")
        self.Widgets = [
            self.diretasLabel, self.manifestacaoImg, self.indiretasb, self.contextob,
            self.motivacaob, self.primeirasb, self.apiceb, self.resolucaob, self.creditosb,
            self.voltarb, self.liderancasb, self.fontesb, self.indiretasTitulo, self.indiretasTexto,
            self.contextoTitulo, self.contextoTexto, self.danteImg, self.motivacaoTitulo, self.motivacaoTexto,
            self.primeirasTitulo, self.primeirasTexto, self.liderancasTitulo, self.liderancasTexto, self.apiceTitulo,
            self.apiceTexto, self.resolucaoTitulo, self.resolucaoTexto, self.fontesTitulo, self.fontesTexto,
            self.creditosTitulo, self.creditosTexto
        ]
        self.telaPrincipalWidgets = []
        self.WidgetsExternas = []
        self.indiretasb.clicked.connect(self.indiretas)
        self.motivacaob.clicked.connect(self.motivacao)
        self.primeirasb.clicked.connect(self.primeiras)
        self.apiceb.clicked.connect(self.apice)
        self.resolucaob.clicked.connect(self.resolucao)
        self.creditosb.clicked.connect(self.creditos)
        self.fontesb.clicked.connect(self.fontes)
        self.liderancasb.clicked.connect(self.liderancas)
        self.contextob.clicked.connect(self.contexto)
        self.voltarb.clicked.connect(self.voltar)
        self.voltarb.hide()
        self.indiretasTitulo.hide()
        self.indiretasTexto.hide()
        self.danteImg.hide()
        self.contextoTexto.hide()
        self.contextoTitulo.hide()
        self.motivacaoTexto.hide()
        self.motivacaoTitulo.hide()
        self.primeirasTexto.hide()
        self.primeirasTitulo.hide()
        self.liderancasTexto.hide()
        self.liderancasTitulo.hide()
        self.apiceTexto.hide()
        self.apiceTitulo.hide()
        self.resolucaoTexto.hide()
        self.resolucaoTitulo.hide()
        self.fontesTexto.hide()
        self.fontesTitulo.hide()
        self.creditosTexto.hide()
        self.creditosTitulo.hide()
        for widget in self.Widgets:
            if not widget.isHidden():
                self.telaPrincipalWidgets.append(widget)
            else:
                self.WidgetsExternas.append(widget)
        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(DiretasJa)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.DiretasJa.setWindowTitle(_translate("DiretasJa", "DiretasJa"))
        self.diretasLabel.setText(_translate("DiretasJa", "<html><head/><body><p><span style=\" font-size:72pt; font-weight:700; font-style:italic; color:#000000;\">DIRETAS JA</span></p></body></html>"))
        self.manifestacaoImg.setText(_translate("DiretasJa", "<html><head/><body><p><img src=\":/newPrefix/manifestacao2.jpg\"/></p></body></html>"))
        self.indiretasb.setText(_translate("DiretasJa", "ELEI\u00c7\u00d5ES \n INDIRETAS", None))
        self.motivacaob.setText(_translate("DiretasJa", "MOTIVA\u00c7\u00c3O", None))
        self.primeirasb.setText(_translate("DiretasJa", "PRIMEIRAS \n MANIFESTA\u00c7\u00d5ES", None))
        self.apiceb.setText(_translate("DiretasJa", "\u00c1PICE", None))
        self.resolucaob.setText(_translate("DiretasJa", "RESOLU\u00c7\u00c3O", None))
        self.creditosb.setText(_translate("DiretasJa", "CR\u00c9DITOS", None))
        self.contextob.setText(_translate("DiretasJa", "PEC n° 05/1983", None))
        self.liderancasb.setText(_translate("DiretasJa", "LIDERAN\u00c7AS", None))
        self.fontesb.setText(_translate("DiretasJa", "FONTES", None))
    def indiretas(self):
        for widget in self.telaPrincipalWidgets:
            widget.hide()
        self.voltarb.show()
        self.indiretasTitulo.show()
        self.indiretasTexto.show()
        self.retranslateUiindiretas()
    def contexto(self):
        for widget in self.telaPrincipalWidgets:
            widget.hide()
        self.voltarb.show()
        self.contextoTitulo.show()
        self.danteImg.show()
        self.contextoTexto.show()
        self.retranslateUicontexto()
    def motivacao(self):
        for widget in self.telaPrincipalWidgets:
            widget.hide()
        self.voltarb.show()
        self.motivacaoTitulo.show()
        self.motivacaoTexto.show()
        self.retranslateUimotivacao()
    def primeiras(self):
        for widget in self.telaPrincipalWidgets:
            widget.hide()
        self.voltarb.show()
        self.primeirasTitulo.show()
        self.primeirasTexto.show()
        self.retranslateUiprimeiras()
    def liderancas(self):
        for widget in self.telaPrincipalWidgets:
            widget.hide()
        self.voltarb.show()
        self.liderancasTitulo.show()
        self.liderancasTexto.show()
        self.retranslateUiliderancas()
    def apice(self):
        for widget in self.telaPrincipalWidgets:
            widget.hide()
        self.voltarb.show()
        self.apiceTitulo.show()
        self.apiceTexto.show()
        self.retranslateUiapice()
    def resolucao(self):
        for widget in self.telaPrincipalWidgets:
            widget.hide()
        self.voltarb.show()
        self.resolucaoTitulo.show()
        self.resolucaoTexto.show()
        self.retranslateUiresolucao()
    def fontes(self):
        for widget in self.telaPrincipalWidgets:
            widget.hide()
        self.voltarb.show()
        self.fontesTitulo.show()
        self.fontesTexto.show()
        self.retranslateUifontes()
    def creditos(self):
        for widget in self.telaPrincipalWidgets:
            widget.hide()
        self.voltarb.show()
        self.creditosTitulo.show()
        self.creditosTexto.show()
        self.retranslateUicreditos()
    def voltar(self):
        for widget in self.telaPrincipalWidgets:
            widget.show()
        for widget in self.WidgetsExternas:
            widget.hide()
    def retranslateUiindiretas(self):
        _translate = QtCore.QCoreApplication.translate
        self.voltarb.setText(_translate("DiretasJa", "VOLTAR", None))
        self.indiretasTitulo.setText(_translate("DiretasJa", "<html><head/><body><p><span style=\" font-size:40pt; font-weight:700; font-style:italic\">ELEIÇÕES INDIRETAS</span></p></body></html>"))
        self.indiretasTexto.setHtml(_translate("DiretasJa", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:23pt; font-weight: 700\">Devido às sequências de atos institucionais, o povo estava gradualmente  perdendo os seus direitos políticos. O principal deles foi o direito de votar para a Presidência da República. Assim, foi instaurado no Brasil um sistema de eleições indiretas, ou seja, o Presidente da República não seria eleito diretamente pelo povo, mas sim por um colégio eleitoral, que durante o regime militar foi o Congresso Nacional.</span></p></body></html>"))
    def retranslateUicontexto(self):
        _translate = QtCore.QCoreApplication.translate
        self.voltarb.setText(_translate("DiretasJa", "VOLTAR", None))
        self.contextoTitulo.setText(_translate("DiretasJa", "<html><head/><body><p><span style=\" font-size:40pt; font-weight:700; font-style:italic\">EMENDA DANTE DE OLIVEIRA</span></p></body></html>"))
        self.contextoTexto.setHtml(_translate("DiretasJa", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight: 700\">Em 1983, o deputado federal Dante de Oliveira (PMDB-MT) apresentou a Proposta de Emenda Constitucional n° 05/1983 ao Congresso Nacional. A PEC, que ficou conhecida como 'Emenda Dante de Oliveira', previa reestabelecer as eleições diretas para a Presidência da República no Brasil.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight: 700\">As manifestações e comícios a favor das eleições diretas ganharam muita força após a apresentação da emenda, fazendo com que a enorme pressão popular afetasse os parlamentares.</span></p></body></html>"))
        self.danteImg.setText(_translate("DiretasJa", "<html><head/><body><p><img src=\":/Dante/dante2.jpg\"/></p></body></html>"))
    def retranslateUimotivacao(self):
        _translate = QtCore.QCoreApplication.translate
        self.voltarb.setText(_translate("DiretasJa", "VOLTAR", None))
        self.motivacaoTitulo.setText(_translate("DiretasJa", "<html><head/><body><p><span style=\" font-size:40pt; font-weight:700; font-style:italic\">MOTIVAÇÃO</span></p></body></html>"))
        self.motivacaoTexto.setHtml(_translate("DiretasJa", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:23pt; font-weight: 700\">Além da Emenda Dante de Oliveira, um outro fator que contribuiu para o crescimento do movimento a favor das eleições diretas foi a grande recessão econômica e o agravamento da inflação. Estima-se que em 1983 a inflação chegou a alcançar a taxa de 239%, e a dívida externa que comprometia boa parte das riquezas nacionais afastava investidores. Ademais, o governo militar atravessava seu período final em meio a uma crise de desgaste que se refletiu em uma crise interna, culminando com a retirada do presidente Figueiredo das articulações para a sucessão presidencial.</span></p></body></html>"))
    def retranslateUiprimeiras(self):
        _translate = QtCore.QCoreApplication.translate
        self.voltarb.setText(_translate("DiretasJa", "VOLTAR", None))
        self.primeirasTitulo.setText(_translate("DiretasJa", "<html><head/><body><p><span style=\" font-size:40pt; font-weight:700; font-style:italic\">PRIMEIRAS MANIFESTAÇÕES</span></p></body></html>"))
        self.primeirasTexto.setHtml(_translate("DiretasJa", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; font-weight: 700\">Ao longo de 1983, eventos em prol das eleições diretas já aconteciam no Brasil. A primeira manifestação pública a favor das eleições diretas ocorreu em no dia 31 de março de 1983, no recém-emancipado município de Abreu e Lima, mas teve baixa adesão. Posteriormente, Ulysses Guimarães parlamentar filiado ao PMDB e um dos principais articuladores do movimento promoveu um debate na Universidade de Goiás. Seu ato teve como resultado a manifestação de aproximadamente 5 mil pessoas a favor da volta das eleições diretas. Outras manifestações aconteceram nesse mesmo ano, como a de São Paulo em 27 de novembro, que alcançou 15 mil pessoas. Entretanto, foi apenas em 1984 que o movimento Diretas Já ganhou massa crítica.</span></p></body></html>"))
    def retranslateUiliderancas(self):
        _translate = QtCore.QCoreApplication.translate
        self.voltarb.setText(_translate("DiretasJa", "VOLTAR", None))
        self.liderancasTitulo.setText(_translate("DiretasJa", "<html><head/><body><p><span style=\" font-size:40pt; font-weight:700; font-style:italic\">LIDERANÇAS</span></p></body></html>"))
        self.liderancasTexto.setHtml(_translate("DiretasJa", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; font-weight: 700\">As principais lideranças das Diretas Já eram políticos, artistas e intelectuais. Dentre os líderes políticos que tiveram suas carreiras interrompidas por algum ato arbitrário da ditadura ou fizeram dos seus mandatos uma resistência, destacaram-se Tancredo Neves, Ulysses Guimarães, Franco Montoro, Mário Covas, Leonel Brizola, Lula e Dante de Oliveira. Dentre outras personalidades em geral que participaram do movimento, Heráclito Fontoura Sobral, Sócrates (futebolista), Fafá de Belém, Chico Boarque, Martinho da Vila e Mário Lago são algumas das várias personalidades que tiveram constante presença nas manifestações e comícios.</span></p></body></html>"))
    def retranslateUiapice(self):
        _translate = QtCore.QCoreApplication.translate
        self.voltarb.setText(_translate("DiretasJa", "VOLTAR", None))
        self.apiceTitulo.setText(_translate("DiretasJa", "<html><head/><body><p><span style=\" font-size:40pt; font-weight:700; font-style:italic\">ÁPICE</span></p></body></html>"))
        self.apiceTexto.setHtml(_translate("DiretasJa", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight: 700\">O ápice do movimento ocorreu durante os quatro primeiros meses de 1984, quando as manifestações estavam tornando-se gigantes. Em 12 de janeiro, Curitiba foi palco do primeiro grande comicio em todo o país da campanha Diretas Já, com cerca de 30 mil pessoas presentes. Em 25 de janeiro, em São Paulo, na Praça da Sé, justamente no dia do aniversário da cidade, o comício conquistou de vez as ruas com o expressivo número de 300 mil pessoas gritando por Diretas Já!. O movimento acumulava cada vez mais pessoas indo às ruas, e isso se mostrou ainda mais claro nas capitais de Minas Gerais, Rio de Janeiro e São Paulo. Em 24 de fevereiro, foi a vez de Belo Horizonte, com a marca de 400 mil pessoas se manifestando na Praça da Rodoviária, no início da Avenida Afonso Pena, tendo o recorde de público até então. As duas maiores manifestações da Diretas Já ocorreram em abril: em 10 de abril, mais de um milhão de pessoas se reuniram nas proximidades da Igreja da Candelária, na cidade do Rio de Janeiro. O estrondoso comício ficou conhecido como 'Comício da Candelária', em referência ao local onde foi realizada a manifestação. Seis dias depois, o Vale do Anhangabaú, na cidade de São Paulo, ficou lotada com 1,5 milhões de manifestantes lutando por eleições diretas, sendo esta a última manifestação da Diretas Já, e também a manifestação que detém o recorde de pessoas de toda a história do movimento.</span></p></body></html>"))
    def retranslateUiresolucao(self):
        _translate = QtCore.QCoreApplication.translate
        self.voltarb.setText(_translate("DiretasJa", "VOLTAR", None))
        self.resolucaoTitulo.setText(_translate("DiretasJa", "<html><head/><body><p><span style=\" font-size:40pt; font-weight:700; font-style:italic\">RESOLUÇÃO</span></p></body></html>"))
        self.resolucaoTexto.setHtml(_translate("DiretasJa", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight: 700\">Mesmo com a alta pressão popular e grande rejeição à Ditadura Militar, a Emenda Dante de Oliveira não foi aprovada na Câmara dos Deputados. A proposta teve 298 votos de deputados favoráveis, sendo que ela precisava de pelo menos 320 votos para que seguisse ao Senado. Com a rejeição da emenda, a eleição para Presidente da República de 1985 foi novamente indireta. Entretanto, articulações da oposição ao regime militar, em especial do PMDB, endossadas pela mídia e com forte apoio popular, racharam a base governista que era maioria no Congresso Nacional, ocasionando a escolha do oposicionista Tancredo Neves (PMDB) como presidente da república, derrotando o candidato Paulo Maluf. Apesar de ter sido eleito, Tancredo jamais tomou posse: sofrendo de um tumor benigno, ele foi hospitalizado no dia anterior a sua posse, e veio ao óbito em 21 de abril de 1985. Assim, o velho aliado dos governos militares acabou sendo o primeiro presidente civil brasileiro desde 1964: José Sarney. Posteriormente, na publicação da Constituição de 1988, a eleição direta foi oficialmente determinada e instaurada para o cargo de Presidente da República.</span></p></body></html>"))
    def retranslateUifontes(self):
        _translate = QtCore.QCoreApplication.translate
        self.voltarb.setText(_translate("DiretasJa", "VOLTAR", None))
        self.fontesTitulo.setText(_translate("DiretasJa", "<html><head/><body><p><span style=\" font-size:40pt; font-weight:700; font-style:italic\">FONTES</span></p></body></html>"))
        self.fontesTexto.setHtml(_translate("DiretasJa", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; text-decoration: underline; background-color:#1e1e1e\">https://mundoeducacao.uol.com.br/historiadobrasil/diretas-ja.htm</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; text-decoration: underline; background-color:#1e1e1e\">https://www.saopaulo.sp.gov.br/conhecasp/historia/diretas-ja/</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; text-decoration: underline; background-color:#1e1e1e\">https://riomemorias.com.br/memoria/comicio-da-candelaria-diretas-ja/</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px;"
                        " -qt-block-indent:0; text-indent:0px; text-decoration: underline; background-color:#1e1e1e\">https://pt.wikipedia.org/wiki/Diretas_J%C3%A1</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; text-decoration: underline; background-color:#1e1e1e\">https://brasilescola.uol.com.br/politica/eleicoes-indiretas-no-brasil.htm</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; text-decoration: underline; background-color:#1e1e1e\">http://g1.globo.com/sao-paulo/noticia/2014/04/famoso-comicio-do-movimento-diretas-ja-completa-30-anos.html</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; text-decoration: underline; background-color:#1e1e1e\">https://www.todamateria.com.br/diretas-ja/</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; text-decoration: underline; background-color:#1e1e1e\">http://querepublicaeessa.an.gov.br/temas/172-diretas-ja-o-povo-volta-as-ruas.html</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-in"
                        "dent:0px; text-decoration: underline; background-color:#1e1e1e\">https://www.gazetadopovo.com.br/vida-publica/curitiba-foi-pioneira-na-campanha-bdzz1yc2vvn0dlfkh33y08r4e/</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; text-decoration: underline; background-color:#1e1e1e\">https://www.tse.jus.br/eleitor/glossario/termos/eleicao-indireta</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; text-decoration: underline; background-color:#1e1e1e\">https://pt.wikipedia.org/wiki/Proposta_de_Emenda_Constitucional_Dante_de_Oliveira</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; text-decoration: underline; background-color:#1e1e1e\">https://www.infoescola.com/historia-do-brasil/emenda-constitucional-dante-de-oliveira/</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; text-decoration: underline; background-color:#1e1e1e\">http://circuitomt.com.br/editorias/perolas-online/140440-emenda-constitucional-de-dante-de-oliveira-que-conduziria-pais-a-eleicao-direta-completa-35-anos.htm"
                        "l</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; text-decoration: underline; background-color:#1e1e1e\">https://www25.senado.leg.br/web/atividade/materias/-/materia/18035</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; text-decoration: underline; background-color:#1e1e1e\">https://memoriaglobo.globo.com/erros/diretas-ja/</p></body></html>", None))
    def retranslateUicreditos(self):
        _translate = QtCore.QCoreApplication.translate
        self.voltarb.setText(_translate("DiretasJa", "VOLTAR", None))
        self.creditosTitulo.setText(_translate("DiretasJa", "<html><head/><body><p><span style=\" font-size:40pt; font-weight:700; font-style:italic\">CRÉDITOS</span></p></body></html>"))
        self.creditosTexto.setHtml(_translate("DiretasJa", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:26pt;\">Autor do Programa: Gabriel de Souza Santos</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:26pt;\">Programa\u00e7\u00e3o: Gabriel de Souza Santos</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:26pt;\">Design: Gabriel de Souza Santos</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:26pt;\">Ano: 2021</p>\n"
"<p style=\" marg"
                        "in-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;  font-size:26pt;\">Ferramentas utilizadas: Python 3.9.6 (Programa\u00e7\u00e3o), Qt Designer (Design), PyQt6, PySide6</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:26pt;\">Código-fonte: https://github.com/Kalest3/DiretasJa</p></body></html>"))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DiretasJa = QtWidgets.QDialog()
    ui = Ui_DiretasJa()
    ui.setupUi(DiretasJa)
    DiretasJa.show()
    sys.exit(app.exec())
